modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="puffish_skills"
version="${version}"
displayName="Pufferfish's Skills"
authors="Pufferfish"
description="Adds a fully configurable skill system to the game."

[[dependencies.puffish_skills]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skills]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
