modLoader="javafml"
loaderVersion="[45,)"
license="LGPL-3.0"

[[mods]]
modId="puffish_skills"
version="${version}"
displayName="Pufferfish's Skills"
authors="Pufferfish"
description="Adds a fully configurable skill system to the game."

[[dependencies.puffish_skills]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skills]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,1.20)"
ordering="NONE"
side="BOTH"
